a = {22,24}
a.add(55)
print(a)
a.update([4,8,9,11,23,5,10])
print(a)
b = {4,9,10}
print(b.issubset(a))
print(a.isdisjoint(b))
print()
print("a union b :", a|b) 
print()
print("a and b : ",a&b)
print()
print("a symmetric_difference of b:",a^b)
print()
print("a difference of b", a-b)
print()
print("b difference of a:",b-a)
print(bool([]))
